# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Boston Azure Datafest 2019
email: adfboston.team@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Boston Azure Datafest is a 1-day conference focused on all aspects of data in Azure. This site contains speaker, sponsor and agenda information and will be the repository for all presentation slides and assets. 
baseurl: "/boston2019" # the subpath of your site, e.g. /blog
url: "http://azuredatafest.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: azuredatafest
github_username:  azuredatafest

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
